version: 2.1

orbs:
  j-cci: heug/jcci@0.8

jobs:
  export-jenkinsfile:
    executor: j-cci/base
    steps:
      - j-cci/setup
  convert:
    executor: j-cci/convertor
    steps:
      - j-cci/install
      - j-cci/convert-to-circleci

workflows:
  version: 2
  jcci:
    jobs:
      - export-jenkinsfile
      - convert:
          requires:
            - export-jenkinsfile
